'use client';

import React from 'react';
import { TORFile } from '@/lib/mock-data';
import { useApp } from '@/context/AppContext';
import { FileText, Download, ShieldCheck } from 'lucide-react';

interface TORDownloadListProps {
  files: TORFile[];
}

export function TORDownloadList({ files }: TORDownloadListProps) {
  const { lang } = useApp();

  const handleDownload = (file: TORFile) => {
    const notice = lang === 'en'
      ? `Mock document from B2G Vendor\n\nFile name: ${file.name}\nSource URL: ${file.url}\nUploaded: ${file.date}\nSize: ${file.size}\n\nThis is a placeholder file generated by the frontend mock — the real ingestion pipeline has not run, so no actual TOR content is attached.`
      : `เอกสารจำลองจากระบบ B2G Vendor\n\nชื่อไฟล์: ${file.name}\nที่อยู่ไฟล์ต้นทาง: ${file.url}\nวันที่อัปโหลด: ${file.date}\nขนาดไฟล์: ${file.size}\n\nนี่คือไฟล์จำลองที่สร้างโดย Frontend Mock เนื่องจากยังไม่มีการรัน Ingestion Pipeline จริง จึงไม่มีเนื้อหา TOR จริงแนบมาด้วย`;

    const blob = new Blob([notice], { type: 'text/plain;charset=utf-8' });
    const objectUrl = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = objectUrl;
    link.download = `${file.name}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(objectUrl);
  };

  return (
    <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-emerald-600" />
          <h3 className="font-bold text-slate-900">
            {lang === 'en' ? 'TOR Specifications & Attachments' : 'เอกสารประกวดราคาและข้อกำหนด TOR'}
          </h3>
        </div>
        <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700 bg-emerald-100 px-2.5 py-1 rounded-full">
          <ShieldCheck className="w-3.5 h-3.5" />
          <span>HTTPS Verified</span>
        </span>
      </div>

      <div className="divide-y divide-slate-200">
        {files.map(file => (
          <div key={file.id} className="py-3 flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold text-xs shrink-0">
                {file.type}
              </div>
              <div>
                <p className="text-sm font-semibold text-slate-900 hover:text-emerald-600 transition-colors cursor-pointer" onClick={() => handleDownload(file)}>
                  {file.name}
                </p>
                <div className="flex items-center gap-3 text-xs text-slate-400 mt-0.5">
                  <span>{file.size}</span>
                  <span>•</span>
                  <span>{lang === 'en' ? 'Uploaded:' : 'วันที่อัปโหลด:'} {file.date}</span>
                </div>
              </div>
            </div>

            <button
              onClick={() => handleDownload(file)}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold rounded-xl bg-white border border-slate-200 text-slate-700 hover:border-emerald-500 hover:text-emerald-600 transition-all shadow-2xs"
            >
              <Download className="w-3.5 h-3.5 text-emerald-600" />
              <span>{lang === 'en' ? 'Download' : 'ดาวน์โหลด'}</span>
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
